jethexa:
# Publish all joint states -----------------------------------
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 100

# Position Controllers ---------------------------------------
    coxa_joint_RR_position_controller:
        type: effort_controllers/JointPositionController
        joint: coxa_joint_RR
        pid: {p: 1350.0, i: 0.0006, d: 170.0, i_clamp_min: -1000.0, i_clamp_max: 1000.0}

    coxa_joint_RM_position_controller:
        type: effort_controllers/JointPositionController
        joint: coxa_joint_RM
        pid: {p: 1350.0, i: 0.0006, d: 170.0, i_clamp_min: -1000.0, i_clamp_max: 1000.0}

    coxa_joint_RF_position_controller:
        type: effort_controllers/JointPositionController
        joint: coxa_joint_RF
        pid: {p: 1350.0, i: 0.0006, d: 170.0, i_clamp_min: -1000.0, i_clamp_max: 1000.0}

    coxa_joint_LR_position_controller:
        type: effort_controllers/JointPositionController
        joint: coxa_joint_LR
        pid: {p: 1350.0, i: 0.0006, d: 170.0, i_clamp_min: -1000.0, i_clamp_max: 1000.0}

    coxa_joint_LM_position_controller:
        type: effort_controllers/JointPositionController
        joint: coxa_joint_LM
        pid: {p: 1350.0, i: 0.0006, d: 170.0, i_clamp_min: -1000.0, i_clamp_max: 1000.0}

    coxa_joint_LF_position_controller:
        type: effort_controllers/JointPositionController
        joint: coxa_joint_LF
        pid: {p: 1350.0, i: 0.0006, d: 170.0, i_clamp_min: -1000.0, i_clamp_max: 1000.0}

    femur_joint_RR_position_controller:
        type: effort_controllers/JointPositionController
        joint: femur_joint_RR
        pid: {p: 1300.0, i: 0.0008, d: 120.0, i_clamp_min: -1000.0, i_clamp_max: 1000.0}

    femur_joint_RM_position_controller:
        type: effort_controllers/JointPositionController
        joint: femur_joint_RM
        pid: {p: 1300.0, i: 0.0008, d: 120.0, i_clamp_min: -1000.0, i_clamp_max: 1000.0}

    femur_joint_RF_position_controller:
        type: effort_controllers/JointPositionController
        joint: femur_joint_RF
        pid: {p: 1300.0, i: 0.0008, d: 120.0, i_clamp_min: -1000.0, i_clamp_max: 1000.0}

    femur_joint_LR_position_controller:
        type: effort_controllers/JointPositionController
        joint: femur_joint_LR
        pid: {p: 1300.0, i: 0.0008, d: 120.0, i_clamp_min: -1000.0, i_clamp_max: 1000.0}

    femur_joint_LM_position_controller:
        type: effort_controllers/JointPositionController
        joint: femur_joint_LM
        pid: {p: 1300.0, i: 0.0008, d: 120.0, i_clamp_min: -1000.0, i_clamp_max: 1000.0}

    femur_joint_LF_position_controller:
        type: effort_controllers/JointPositionController
        joint: femur_joint_LF
        pid: {p: 1300.0, i: 0.0008, d: 120.0, i_clamp_min: -1000.0, i_clamp_max: 1000.0}

    tibia_joint_RR_position_controller:
        type: effort_controllers/JointPositionController
        joint: tibia_joint_RR
        pid: {p: 1250.0, i: 0.001, d: 66.0, i_clamp_min: -1000.0, i_clamp_max: 1000.0}

    tibia_joint_RM_position_controller:
        type: effort_controllers/JointPositionController
        joint: tibia_joint_RM
        pid: {p: 1250.0, i: 0.001, d: 66.0, i_clamp_min: -1000.0, i_clamp_max: 1000.0}

    tibia_joint_RF_position_controller:
        type: effort_controllers/JointPositionController
        joint: tibia_joint_RF
        pid: {p: 1250.0, i: 0.001, d: 66.0, i_clamp_min: -1000.0, i_clamp_max: 1000.0}

    tibia_joint_LR_position_controller:
        type: effort_controllers/JointPositionController
        joint: tibia_joint_LR
        pid: {p: 1250.0, i: 0.001, d: 66.0, i_clamp_min: -1000.0, i_clamp_max: 1000.0}

    tibia_joint_LM_position_controller:
        type: effort_controllers/JointPositionController
        joint: tibia_joint_LM
        pid: {p: 1250.0, i: 0.001, d: 66.0, i_clamp_min: -1000.0, i_clamp_max: 1000.0}

    tibia_joint_LF_position_controller:
        type: effort_controllers/JointPositionController
        joint: tibia_joint_LF
        pid: {p: 1250.0, i: 0.001, d: 66.0, i_clamp_min: -1000.0, i_clamp_max: 1000.0}

