# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: todo_group_name
  joint_model_group_pose: todo_state_name
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - coxa_joint_LF
    - femur_joint_LF
    - tibia_joint_LF
    - coxa_joint_LM
    - femur_joint_LM
    - tibia_joint_LM
    - coxa_joint_LR
    - femur_joint_LR
    - tibia_joint_LR
    - coxa_joint_RF
    - femur_joint_RF
    - tibia_joint_RF
    - coxa_joint_RM
    - femur_joint_RM
    - tibia_joint_RM
    - coxa_joint_RR
    - femur_joint_RR
    - tibia_joint_RR
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: body_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - coxa_joint_LF
      - femur_joint_LF
      - tibia_joint_LF